import React, { useState, useEffect } from "react";
import { SERVER_URL } from "../constants";
/**
 * Required fields for an assignment DTO =>
 * int id (autogenerated for assignment)
 * string assignmentName
 * string dueDate
 * string courseTitle
 * int courseId
 */

const AddAssignment = (props) => {
  const [name, setName] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [title, setTitle] = useState("");

  const headers = ["Name", "Due Date", "Course Title"];

  const onChangeName = (e) => {
    setName(e.target.value);
  };

  const onChangeDate = (e) => {
    console.log(e.target.value);
    setDueDate(e.target.value);
  };

  const onChangeTitle = (e) => {
    setTitle(e.target.value);
  };

  const handleSubmit = () => {
    
  }

  return (
    <div>
      <h3>Create Assignment</h3>
      <div margin="auto">
        <table className="Center">
          <thead>
            <tr>
              {headers.map((title, idx) => (
                <th key={idx}>{title}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <input
                  name="name"
                  value={name}
                  type="text"
                  placeholder="Assignment Name"
                  onChange={(e) => onChangeName(e)}
                />
              </td>
              <td>
                <input
                  name="date"
                  value={dueDate}
                  type="date"
                  placeholder="YYYY-MM-DD"
                  onChange={(e) => onChangeDate(e)}
                />
              </td>
              <td>
                <input
                  name="title"
                  value={title}
                  type="text"
                  placeholder="DEP - COURSE"
                  onChange={(e) => onChangeTitle(e)}
                />
              </td>
            </tr>
          </tbody>
        </table>
        <br />
        <button
          id="sgrade"
          type="button"
          margin="auto"
          onClick={handleSubmit}
        >
          Submit
        </button>
      </div>
    </div>
  );
};

export default AddAssignment;
