import React, { useState, useEffect } from "react";
import { SERVER_URL } from "../constants";
/**
 * Required fields for an assignment DTO =>
 * int id (autogenerated for assignment)
 * string assignmentName
 * string dueDate
 * string courseTitle
 * int courseId
 */

const AddAssignment = (props) => {
  const [assignmentName, setAssignmentName] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [courseTitle, setCourseTitle] = useState("");
  const [courseId, setCourseId] = useState(0);

  const headers = ["Name", "Due Date", "Course Title", "Course ID"];

  const onChangeName = (e) => {
    setAssignmentName(e.target.value);
  };

  const onChangeDate = (e) => {
    console.log(e.target.value);
    setDueDate(e.target.value);
  };

  const onChangeTitle = (e) => {
    setCourseTitle(e.target.value);
  };

  const onChangeId = (e) => {
    setCourseId(e.target.value);
  };

  const handleSubmit = async () => {
    const dtoObject = {
      assignmentName,
      dueDate,
      courseTitle,
      courseId,
    };

    fetch(`${SERVER_URL}/assignment`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(dtoObject),
    })
      .then((response) => {
        if (response.ok) return response.text();
        else throw new Error(`POST assignment error: ${response.statusText}`);
      })
      .then((data) =>
        console.log(`Created assignment with id: ${parseInt(data, 10)}`)
      );
  };

  return (
    <div>
      <h3>Create Assignment</h3>
      <div margin="auto">
        <table className="Center">
          <thead>
            <tr>
              {headers.map((title, idx) => (
                <th key={idx}>{title}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <input
                  name="name"
                  value={assignmentName}
                  type="text"
                  placeholder="Assignment Name"
                  onChange={(e) => onChangeName(e)}
                />
              </td>
              <td>
                <input
                  name="date"
                  value={dueDate}
                  type="date"
                  placeholder="YYYY-MM-DD"
                  onChange={(e) => onChangeDate(e)}
                />
              </td>
              <td>
                <input
                  name="title"
                  value={courseTitle}
                  type="text"
                  placeholder="DEP - COURSE"
                  onChange={(e) => onChangeTitle(e)}
                />
              </td>
              <td>
                <input
                  name="id"
                  value={courseId}
                  type="number"
                  placeholder="00000000"
                  onChange={(e) => onChangeId(e)}
                />
              </td>
            </tr>
          </tbody>
        </table>
        <br />
        <button id="sgrade" type="button" margin="auto" onClick={handleSubmit}>
          Submit
        </button>
      </div>
    </div>
  );
};

export default AddAssignment;
